server:
  port: 8090

spring:
  redis:
    database: 0
    host:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password:
    port: 6379
    timeout: 3000

wx:
  mp:
    useRedis: true
    configs:
      - appId: 2222 # 第二个公众号的appid，以下同上
        secret: 1111
        token: 111
        aesKey: 111
