server:
  port: 8090

spring:
  redis:
    database: 0
    host:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password:
    port: 6379
    timeout: 3000

wx:
  mp:
    useRedis: true
    configs:
    - appId:  # 第一个公众号的appid
      secret:  # 公众号的appsecret
      token:  # 接口配置里的Token值
      aesKey:  # 接口配置里的EncodingAESKey值
    - appId:  # 第一个公众号的appid
      secret:  # 公众号的appsecret
      token:  # 接口配置里的Token值
      aesKey:  # 接口配置里的EncodingAESKey值

config:
  thread:
    enabled: true
    threadPrefix: Async-Service
    corePoolSize: 10
    maxPoolSize: 20
    queueCapacity: 100
    keepAliveSeconds: 15
  purpose:
    remind: wx3dffb886eea05a48